---
  - name: Create sources directory if it does not exist
    file:
      path: /home/pi/sources
      state: directory
  
  - name: Get stats of the arduino-cli binary to check it exists 
    ansible.builtin.stat:
      path: /usr/local/bin/arduino-cli
    register: st
  
  - name: Print a debug message if arduino-cli not installed
    ansible.builtin.debug:
      msg: "arduino-cli is not installed"
    when: st.stat.exists == False
    
  - git:
      repo: https://github.com/practable/penduino.git
      dest: /home/pi/sources/penduino
      update: yes
     
  - name: Update core index arduino
    command: arduino-cli core update-index

  - name: Install avr core arduino
    command: arduino-cli core install arduino:avr

  - name: Compile penduino firmware
    command: arduino-cli compile --fqbn arduino:avr:nano Penduino/ 
    args:
      chdir: /home/pi/sources/penduino/fw

  - name: Load penduino firmware onto arduino
    command: arduino-cli upload --port /dev/ttyUSB0 --fqbn arduino:avr:nano Penduino/ 
    args:
      chdir: /home/pi/sources/penduino/fw
    

